### ISSUE TITLE
Actions не работают для окружений Proof, Theorem и т.д.

### ISSUE THREAD

**Issue by mkakanov** [kakanovma/ITMOBeamer#1]
![image](https://user-images.githubusercontent.com/59731445/92030284-806cfb00-ed6f-11ea-8275-1302862845f9.png)
В код окружения нужно добавить actionenv, но пока не понятно как он работает... А то не работают overlays.         
 ```
\begin{enumerate}[<+-|alert@+>]
                \item
                Effects that control
                \item
                when text is displayed
                \item
                are specified with <> and a list of slides.
\end{enumerate}
```

**Comment by kakanovma** [comment]
Теперь работают overlays для окружений, если в явном виде указывать параметр
```
\begin{theorem}[Fermat's little theorem]<2>
        For a prime~\(p\) and \(a \in \mathbb{Z}\) it holds that \(a^p \equiv a \pmod{p}\).
\end{theorem}
```
Но для примера описанного выше все еще проблема не решена.
